brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('todos/', include('todos.urls')),
]

todos/urls.py
from django.urls import path
from .views import todo_list, todo_list_detail, todo_list_create, todo_list_update, todo_list_delete, todo_item_create, todo_item_update

app_name = 'todos'

urlpatterns = [
    path('', todo_list, name='todo_list_list'),
    path('todo_list_detail/<int:id>/', todo_list_detail, name='todo_list_detail'),
    path('todo_list_create/', todo_list_create, name='todo_list_create'),
    path('todo_list_update/<int:id>/edit/', todo_list_update, name='todo_list_update'),
    path('todo_list_delete/<int:id>/delete/', todo_list_delete, name='todo_list_delete'),
    path('todo_item_create/items/create', todo_item_create, name='todo_item_create'),
    path('todo_item_update/items/<int:id>/edit/', todo_item_update, name='todo_item_update'),
]

todos/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        TodoList, related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/forms.py
from django import forms
from .models import TodoList
from .models import TodoItem

class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ['name']

class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = [
            'task',
            'due_date',
            'is_completed',
            'list'
        ]

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import TodoList
from .forms import TodoListForm
from .forms import TodoItemForm
from .models import TodoItem

# Create your views here.
def todo_list(request):
    todo_lists = TodoList.objects.all()
    return render(request, 'todos/todo_list_list.html', {'todo_lists': todo_lists})

def todo_list_detail(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    return render(request, 'todos/todo_list_detail.html', {'todo_list': todo_list})

def todo_list_create(request):
    if request.method == 'POST':
        form = TodoListForm(request.POST)
        if form.is_valid():
            new_todo = form.save()
            return redirect('todos/todo_list_detail', id=new_todo.id)
    else:
        form = TodoListForm()

    context = {
        "form": form
    }

    return render(request, 'todos/todo_list_create.html', context)

def todo_list_update(request, id):
    update_list = get_object_or_404(TodoList, id=id)

    if request.method == 'POST':
        form = TodoListForm(request.POST, instance=update_list)
        if form.is_valid():
            update_list = form.save()
            return redirect('todos/todo_list_update', id=update_list.id)
    else:
        form = TodoListForm(instance=update_list)

    context = {
        "form": form
    }

    return render(request, 'todos/todo_list_update.html', context)

def todo_list_delete(request, id):
    delete_list = TodoList.objects.get(id=id)
    if request.method == 'POST':
        delete_list.delete()
        return redirect('todos/todo_list_delete')

    return render(request, 'todos/todo_list_delete.html')

def todo_item_create(request):
    if request.method == 'POST':
        form = TodoItemForm(request.POST)
        if form.is_valid():
            create_todo = form.save
            return redirect('todo_list_detail', id=create_todo.list.id)
    else:
        form = TodoItemForm()

    context = {
        "form": form
    }

    return render(request, 'todos/todo_item_create.html', context)

def todo_item_update(request):
    update_item = get_object_or_404(TodoItem, id=id)

    if request.method =='POST':
        form = TodoItemForm(request.POST, instance=update_item)
        if form.is_valid():
            form.save()
            return redirect('todos/todo_list_detail', id=update_item.id)
    else:
        form = TodoItemForm(instance=update_item)
    context = {
        "form": form
    }

    return render(request, 'todos/todo_item_update.html', context)

todos/templates/todos/todo_item_create.html
<!DOCTYPE html>
<html>
<head>
    <title>Create new item</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new item</h1>
            <form method="post">
                <input type="text" name="task">
                <input type="text" name="due_date">
                <input type="checkbox" name="is_completed">
                <select name="list">List</select>
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_item_update.html
<!DOCTYPE html>
<html>
<head>
    <title>Update Todo Item</title>
</head>
<body>
    <main>
        <div>
            <h1>Update item</h1>
            <form method="post">
                <input type="text" name="task">
                <br>
                <input type="text" name="due_date">
                <br>
                <input type="checkbox" name="is_completed">
                <select name="list">
                </select>
                <br>
                <button type="submit">Update</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_list_create.html
<!doctype>
<html>
    <head>
        <title>Create Todo List</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create a new list</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="text" name="name">
                    <button type="submit">Create</button>
                </form>
            </div>
        </main>
    </body>
    </html>

todos/templates/todos/todo_list_delete.html
<!doctype html>
<html>
    <head>
        <title>Delete Todo List</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Are you sure?</h1>
                <form metohd="post">
                    {% csrf_token %}
                    <button type="submit">Delete</button>
                </form>
            </div>
        </main>
    </body>
    </html>

todos/templates/todos/todo_list_detail.html
<!doctype html>
<html>
    <head>
        <title>To-Do List Details</title>
    </head>
    <body>
        <main>
            <div>
                <h1>To-Do List: {{ todo_list.name }}</h1>

                <p>
                    <a href="{% url 'todos:todo_list_update' todo_list.id %}">Edit</a>
                </p>
                <p>
                    <a href="{% url 'todos:todo_list_delete' todo_list.id %}">Delete</a>
                </p>
                <h2>Tasks</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Task</th>
                            <th>Due Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in todo_list.tasks.all %}
                        <tr>
                            <td>
                                <a href="{% url 'todos:todo_item_update' task.id %}">{{ task.title }}</a>
                            </td>
                            <td>{{ task.due_date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </main>
    </body>
    </html>

todos/templates/todos/todo_list_list.html
<!doctype html>
<html>
    <head>
        <title>Todo List</title>
    </head>
    <body>
        <main>
            <div>
                <h1>My Lists</h1>
                <div>
                    <p>
                        <a href="{% url 'todos:todo_item_create' %}">Create a new item</a>
                    </p>
                    <p>
                        <a href="{% url 'todos:todo_list_create' %}">Create a new list</a>
                    </p>
                </div>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Numbers of items</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for todo_list in todo_lists %}
                            <tr>
                                <td>
                                    <a href="{% url 'todos:todo_list_detail' todo_list.id %}">{{ todo_list.name }}</a>
                                </td>
                                <td>{{ todo_list.items.all|length }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </main>
        </body>
    </html>

todos/templates/todos/todo_list_update.html
<!doctype html>
<html>
    <head>
        <title>Update Todo List</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Update list</h1>
                <form method="post">
                    <input type="text" name="name">
                    <button type="submit">Update</button>
                </form>
            </div>
        </main>
    </body>
</html>